### ISSUE TITLE
OER Resources Card Length

### ISSUE THREAD

**Issue by vighneshmufc** [CLIxIndia-Dev/clixoer#23] opened 2020-07-31 13:12 UTC
**OER Resources Card Length Longer then Others**
As we can see in the SS below . For eg. The length of Card of Geogebra in Tamil is more than others. Please Change the text size to Ensure all cards look same.

**To Reproduce**
1. Go to 'http://staging-clixoer.tiss.edu'
2. Click on 'Cool-OER or http://staging-clixoer.tiss.edu/cool/oer'
3. Scroll down to 'Geogebra in Tamil'

**Expected behavior**
All cards should all be of same length

**Screenshots**
![Screenshot (283)](https://user-images.githubusercontent.com/14256897/89038054-3bfbd300-d35d-11ea-8c3e-da9dcc887e35.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [e.g. 84]

**Comment by yogeshu** [comment] 2020-08-10 03:21
about this issue  - #1 Card Length is not fixed so it varies according to the content . if we manually set the random height with a change in value's it affects all cards and there will be gap and space inside the card. check this image below to understand it - ( image in the group check )

**Comment by yogeshu** [comment] 2020-08-13 08:24
![Screenshot from 2020-08-03 12-16-44](https://user-images.githubusercontent.com/32289745/90111566-73f71300-dd6c-11ea-8afd-4d7b60851044.png)

**Comment by yogeshu** [comment] 2020-09-08 09:41
@vighneshmufc check

**Comment by vighneshmufc** [comment] 2020-09-09 05:18
Where are these changes done ?
I dont see it anywhere

**Comment by yogeshu** [comment] 2020-09-09 05:43
I have commented on the cause of Card Height! why it will be not fixed if we make all height as same

**Comment by yogeshu** [comment] 2020-09-09 05:44
The image Included is for demonstration of what I said in the comment that is giving a manual height make such a gap in content

**Comment by vighneshmufc** [comment] 2020-09-09 06:39
@SadaqatMulla Please take a call

**Comment by SadaqatMulla** [comment] 2020-09-09 07:43
@vighneshmufc the length of OER card is changing mainly due to tags. While the tags will be same across languages In one/some languages the word lengths may vary. However the length should NOT vary too much, we can say mostly a one row difference of length might happen, as in the of GeoGebra.
 @yogeshu can rearrange tags for particular resources whenever such a need arises to keep consistency.
Good observations @vighneshmufc from consistency point of view, however currently it is in tolerable limits and isn't affecting usability/user experience much. So, for now we can close this keeping note of above considerations.

**Closed** 2021-06-17 11:45 UTC
Labels: bug, frontend, lowpriority
